or1k: Fix compilation for __OR1K_MULTICORE__ builds
When building newlib for multicore environments we specify __OR1K_MULTICORE__
which switches the build to allocate one struct _or1k_reent per CPU
dynamiocally.

This was using a strange definition of (*_or1k_reent)[], and causing
the following compiler error:

    ./gnu-toolchain/newlib/libgloss/or1k/impure.c: In function ‘_or1k_reent_init’:
    ./gnu-toolchain/newlib/libgloss/or1k/impure.c:121:21: error: assignment to ‘struct ..
      121 |         _or1k_reent = (struct _or1k_reent*) _sbrk_r(0, memsize);
	  |

Fix this compiler error by changing the or1k_reent definition to a pointer
to structs.

Signed-off-by: Stafford Horne <shorne@gmail.com>